### ISSUE TITLE
 Exception when pc comes back from sleep

### ISSUE THREAD

**Issue by bmrussell** [bmrussell/LGBattery#2]
```
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 461, in finish_socket_func
OSError: [WinError 64] The specified network name is no longer available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "websockets\legacy\protocol.py", line 963, in transfer_data
  File "websockets\legacy\protocol.py", line 1033, in read_message
  File "websockets\legacy\protocol.py", line 1108, in read_data_frame
  File "websockets\legacy\protocol.py", line 1165, in read_frame
  File "websockets\legacy\framing.py", line 68, in read
  File "asyncio\streams.py", line 734, in readexactly
  File "asyncio\streams.py", line 527, in _wait_for_data
  File "asyncio\proactor_events.py", line 286, in _loop_reading
  File "asyncio\windows_events.py", line 798, in _poll
  File "asyncio\windows_events.py", line 465, in finish_socket_func
ConnectionResetError: [WinError 64] The specified network name is no longer available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lgbattery.py", line 155, in <module>
  File "asyncio\runners.py", line 194, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 664, in run_until_complete
  File "lgbattery.py", line 100, in watch_battery
  File "websockets\legacy\protocol.py", line 568, in recv
  File "websockets\legacy\protocol.py", line 939, in ensure_open
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by bmrussell** [comment]
Fixed v1.0.5
